### ISSUE TITLE
Check-effect-interaction fix while calling payFees on switchboard

### ISSUE THREAD

**Issue by ameeshaagrawal** [SocketDotTech/socket-DL#161]
https://gist.github.com/ameeshaagrawal/2450e4993b2708b1ae0326e3aea43c1b#file-slither-output-L155

In outbound(), there is a possibility that switchboard can consume extra execution fee passed to execution manager. To solve this, we have decided to rearrange `_deductFee()` to the end of outbound() call and pay fees to switchboard at the end.

**Comment by arthcp** [comment]
Fixed.
