### ISSUE TITLE
Not all contracts are verified

### ISSUE THREAD

**Issue by gpersoon** [SocketDotTech/socket-DL#176]
**Describe the bug**
Not all contract are verified on https://goerli.etherscan.io

**To Reproduce**
See the following contracts:
- [Capacitors](https://goerli.etherscan.io/find-similar-contracts?a=0xeA1166b60196Cd3335880A4173517881CE0294B1&lvl=5)
- [Decapacitors](https://goerli.etherscan.io/find-similar-contracts?a=0xA44206EEA8bCDfB6b63C19963d87CF8d36A2BE5a&lvl=5)
- [SocketBatcher](https://goerli.etherscan.io/address/0xCc7eAe7b35a85EaE46aCd852426FaC3b1D3bD57b#code)
- [CapacitorFactory](https://goerli.etherscan.io/address/0x3504C46095dBB85C01571E8Fa9DE5C07501D4c02#code)

**Expected behavior**
The sourcecode is verified on https://goerli.etherscan.io as well as on the other chains.

**Additional context**
-

**Comment by arthcp** [comment]
We are facing errors with verifying these contracts programmatically, manual verification still works.
Will do it for production deployments.
