### ISSUE TITLE
Query the `capacitorType`

### ISSUE THREAD

**Issue by gpersoon** [SocketDotTech/socket-DL#177]
**Is your feature request related to a problem? Please describe.**
The capacitors on Goerli are not verified, see https://github.com/SocketDotTech/socket-DL/issues/176
So its difficult to know which capacitor is used. Then I tried to query them, but that is also not possible.

**Describe the solution you'd like**
Query the `capacitorType` of a `SwitchBoard` or a `capacitor`.

**Describe alternatives you've considered**
Check etherscan, see above.

**Additional context**
-

**Comment by arthcp** [comment]
We plan to verify all the contracts for production deployments.
