### ISSUE TITLE
Switchboard signatures can be replayed on same chain

### ISSUE THREAD

**Issue by ameeshaagrawal** [SocketDotTech/socket-DL#178]
**Describe the bug**
SwitchboardBase has functions `tripPath`, `tripGlobal`, `untrip` and `untripPath` which takes signature as input to check if sender is valid or not. If one of the functions is called on FastSwitchboard, the same signature can be replayed on OptimisticSwitchboard.

**Expected behavior**
The signature should be unique for all actions involved in Socket to prevent replay attacks.

**Solution**
We are adding `address(this)` to digest to have a unique digest for all switchboards.

**Comment by gpersoon** [comment]
In think the same is true for all partial clones of `FastSwitchboard`, `OptimisticSwitchboard` and `NativeSwitchboard`,
where the same function interfaces are use.
For example if there would be another Switchboard that uses `attest()`, that could be replayed as well.
So somehow the type/version of the Switchboards should be included in the signature.

**Comment by arthcp** [comment]
Fixed
