### ISSUE TITLE
Transmitter Signature Replay on Socket Redeployment

### ISSUE THREAD

**Issue by ameeshaagrawal** [SocketDotTech/socket-DL#179]
**Describe the bug**
Transmitter signature can be replayed to re-propose a packet if the Socket core is redeployed with same transmitter set. As we plan to make the executor role open for all, this bug can be a high severity bug. 

```solidity
        (address transmitter, bool isTransmitter) = transmitManager__
            .checkTransmitter(
                uint32(_decodeSlug(packetId_)),
                keccak256(abi.encode(chainSlug, packetId_, root_)),
                signature_
            );
```

**Proposed Solution**
Current solution is to include a version to this signature which can be set with deployment of Socket contracts. Hence the code will look like:

```solidity
        (address transmitter, bool isTransmitter) = transmitManager__
            .checkTransmitter(
                uint32(_decodeSlug(packetId_)),
                keccak256(abi.encode(version, chainSlug, packetId_, root_)),
                signature_
            );
```

Plans to include EIP-712 is in discussion, feel free to suggest or open a thread on same.

**Comment by arthcp** [comment]
we have addressed this by introducing version for seal/propose and contract address for other signatures.
