### ISSUE TITLE
Use solidity for `_splitSignature`

### ISSUE THREAD

**Issue by gpersoon** [SocketDotTech/socket-DL#182]
**Is your feature request related to a problem? Please describe.**
The function `_splitSignature` uses assembly which is more difficult to understand and maintain.
[SignatureVerifierLib.sol#L61-L70](https://github.com/SocketDotTech/socket-DL/blob/master/contracts/libraries/SignatureVerifierLib.sol#L61-L70)
```solidity
    function _splitSignature(
        bytes memory signature_
    ) private pure returns (bytes32 r, bytes32 s, uint8 v) {
        if (signature_.length != 65) revert InvalidSigLength();
        assembly {
            r := mload(add(signature_, 0x20))
            s := mload(add(signature_, 0x40))
            v := byte(0, mload(add(signature_, 0x60)))
        }
    }
```

**Describe the solution you'd like**
Preferably use a solidity version. For example the following:
```solidity
 function _splitSignature(bytes calldata signature_) public pure returns (bytes32 r, bytes32 s, uint8 v) {
        if (signature_.length != 65) revert InvalidSigLength();
        r = bytes32(signature_[0:32]);
        s = bytes32(signature_[32:64]);
        v = uint8(bytes1(signature_[64:65]));
    }
```
Note: The function calling `_splitSignature()` should also receive the `signature_` as `calldata` and pass it along.

**Describe alternatives you've considered**
Keeping it as is.

**Additional context**

**Comment by arthcp** [comment]
We have changed contracts to use openzeppelin's ECDSA lib instead of inhouse code.
