### ISSUE TITLE
Function `getPlugConfig()` can returns all 0s 

### ISSUE THREAD

**Issue by gpersoon** [SocketDotTech/socket-DL#183]
**Describe the bug**
Function `getPlugConfig()` returns all 0s when accidentally the wrong Slug is used (for example with copy/paste errors).
The same occurs when the wrong `plugAddress_` is used.

**To Reproduce**
Call `getPlugConfig(localPlug,localSlug);`

**Expected behavior**
Perhaps this is as designed, in that case it would be good to add a comment.
Could also do a revert if no information is present.

**Additional context**
https://github.com/SocketDotTech/socket-DL/blob/master/contracts/socket/SocketConfig.sol#L173-L198
```solidity
    function getPlugConfig(
        address plugAddress_,
        uint256 siblingChainSlug_
    )
        external
        view
        returns (
            address siblingPlug,
            address inboundSwitchboard__,
            address outboundSwitchboard__,
            address capacitor__,
            address decapacitor__
        )
    {
        PlugConfig memory _plugConfig = _plugConfigs[plugAddress_][siblingChainSlug_]; // all 0s if wrong Slug is used

        return (
            _plugConfig.siblingPlug,
            address(_plugConfig.inboundSwitchboard__),
            address(_plugConfig.outboundSwitchboard__),
            address(_plugConfig.capacitor__),
            address(_plugConfig.decapacitor__)
        );
    }
```

**Comment by arthcp** [comment]
It is a view function so it feels fine to return default values.
