### ISSUE TITLE
Attest used in multiple ways

### ISSUE THREAD

**Issue by gpersoon** [SocketDotTech/socket-DL#185]
**Describe the bug**
The functions `seal()` and `propose()` use the errors `AlreadyAttested()` and `InvalidAttester()`.

This is misleading, because there is also a function Attest in `FastSwitchboard`.

**To Reproduce**
See source code below.

**Expected behavior**
Suggested solution:
```diff
-error AlreadyAttested();
+error AlreadyProposed();
-error InvalidAttester();
+error InvalidTransmitter();
```
**Additional context**

[SocketSrc.sol#L181-L201](https://github.com/SocketDotTech/socket-DL/blob/master/contracts/socket/SocketSrc.sol#L181-L201):
```solidity
function seal(...) ... {
    ...
    if (!isTransmitter) revert InvalidAttester();
    ...
}
```
[SocketDst.sol#L80-L100](https://github.com/SocketDotTech/socket-DL/blob/master/contracts/socket/SocketDst.sol#L80-L100):
```solidity
function propose(...) ... {
    if (packetIdRoots[packetId_] != bytes32(0)) revert AlreadyAttested();
    ...
   if (!isTransmitter) revert InvalidAttester();
   ...
}
```

[FastSwitchboard.sol#L67-L88](https://github.com/SocketDotTech/socket-DL/blob/master/contracts/switchboard/default-switchboards/FastSwitchboard.sol#L67-L88):
```solidity
function attest(...) ... {
    ...
    emit PacketAttested(packetId_, watcher);
}
```

**Comment by arthcp** [comment]
Changed the names for consistency.
