### ISSUE TITLE
No good way to close a connection

### ISSUE THREAD

**Issue by gpersoon** [SocketDotTech/socket-DL#186]
**Describe the bug**
Disconnecting (e.g. the reverse of a `connect()` ) is difficult to do.
The closest way is to do this:
```solidity
connect(siblingChainSlug,address(0),Switch,Switch);
```
However, in this situation `outbound()` still functions and tries to send to `address(0)`.

**To Reproduce**

**Expected behavior**
I would expect a way to close the connection, after which `outbound()` doesn't work.
Consider implementing a close functions.

**Additional context**

**Comment by arthcp** [comment]
Adding address(0) check in outbound.
