### ISSUE TITLE
Allowing users to pass msg.value across chains

### ISSUE THREAD

**Issue by tHeMaskedMan981** [SocketDotTech/socket-DL#190]
##  Motivation

Currently users don't have a way to add msg.value in the inbound() call to the destination plug. We can provide this feature by making the following changes - 

- include a field `msgValue` in the SocketSrc.outbound() function. This will also be a part of PackedMessage.  
- msg.value on source chain should be >= msgValue*relativeNativeTokenPrice + transmissionFees + switchboardFees + minExecutionFees
- Extra msg.value will be part of the execution fees. 
- will need to maintain relativeNativeTokenPrice in a mapping in gasPriceOracle contract to allow onchain calculation. 
- add a check on SocketDst to make sure executor is sending correct `msgValue` in the execution transaction. 
- update the dl-api to include a parameter of `msgValue` for estimating total native tokens to be deposited on source chain. 

## Things to discuss - 

- if the value is more than a certain threshold, our relayer wont be able to relay in the current state (check biconomy/gelato). will have to keep certain executors/relayers for relaying high value transactions. 

- The relative price of native tokens may vary, as gasPriceOracle can also be a bit outdated or bridging may take time(for ex. native bridges). In such cases, executors can refuse to execute a transaction. In such cases, either socket will execute the transaction, or the user can do it themselves by bridging the funds. 

- once someone executes a message, we need to keep a log of which executor executed which message, and then transfer fees to the executer either on the source chain, or the destination chain. 

- can we have an option for the user to get refund of the msgValue funds if the message is not executed on destination chain after a timeout period? Will need to make sure user can't get the refund is message is already executed on the destination.

**Comment by tHeMaskedMan981** [comment]
updates - 
- we can keep the relativeNativeToken Oracle inside execution manager. 
- we can keep an extra bytes field for all the specific extra instructions. 
- we will have a threshold cap on value on all chains. can store this in execution manager. 
- will keep the value threshold low for now, so relayers can process.  later combine with refuel (for socket executions). other executers will have to send msg.value themselves. 
- we can keep the msgValue related checks inside Execution manager. the plug will mention in the request how much value they want on the destination plug. The execution manager will verify if they have passed enough msg.value to cover the cost of native gas token passed as value on destination. If not, then execution manager will revert. 
- msg.value should be a part of packedMessage. 
- skipping fee distribution logic for now, will keep a log on destination side, and send a message through reverse plug to distribute fees on source chain.

**Comment by vaibhavchellani** [comment]
> we can keep an extra bytes field for all the specific extra instructions.

think we can make do with bytes32

**Comment by vaibhavchellani** [comment]
> msg.value should be a part of packedMessage.

think we can make the entire bytes32 in packedMessage
