### ISSUE TITLE
Potential signature replay in `SignatureVerifierLib.recoverSignerFromDigest()`

### ISSUE THREAD

**Issue by smitrajput** [SocketDotTech/socket-DL#254]
**Describe the bug**
Potential signature replay due to missing check on 's' in [`SignatureVerifierLib.recoverSignerFromDigest()`](https://github.com/SocketDotTech/socket-DL/blob/master/contracts/libraries/SignatureVerifierLib.sol#L49):
```solidity
    function recoverSignerFromDigest(
        bytes32 digest_,
        bytes memory signature_
    ) internal pure returns (address signer) {
        bytes32 digest = keccak256(
            abi.encodePacked("\x19Ethereum Signed Message:\n32", digest_)
        );
        (bytes32 sigR, bytes32 sigS, uint8 sigV) = _splitSignature(signature_);

        // recovered signer is checked for the valid roles later
        signer = ecrecover(digest, sigV, sigR, sigS);
    }
```
with something like [this in Openzeppelin's ECDSA lib](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol#L156):
```solidity
        if (uint256(s) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) {
            return (address(0), RecoverError.InvalidSignatureS, s);
        }

        // If the signature is valid (and not malleable), return the signer address
        address signer = ecrecover(hash, v, r, s);
```
before the `ecrecover()` call, to prevent malleable signatures with `s` on upper-half of the secp256k1 constant (`0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141`).

**To Reproduce**
Send forged signature with its `s` calculated as `0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141 - originalSignatureS`, and `v` flipped to 28 if original sigature's `v` was 27 (and vice-versa).

**Expected behavior**
Forged signature will be considered valid too.

**Comment by tHeMaskedMan981** [comment]
Hey @smitrajput , thanks for submitting the issue.
All the state updates that we do with signatures  are either nonce based (trip, untrip, fee update), or have other state-related checks to avoid replay of signatures(packet count for seal, messageExecuted for execute, etc), so replay of malleable signatures isn't a problem as of now. We earlier wanted to keep the sig library minimal so decided to use this. However, we will use some light standard library to avoid any issues in the future.

**Comment by smitrajput** [comment]
touché

**Comment by arthcp** [comment]
Changed to use openzeppelin ECDSA lib for address recovery.
Rest we think is fine as is.
Closing the issue.
