### ISSUE TITLE
Routing Bungee Exchange

### ISSUE THREAD

**Issue by thegasbill** [SocketDotTech/socket-DL#352]
In some cases, selecting a specific destination chain on (multitx)Bungee Exchange prompts a message stating that the route is unavailable. This forces users to try every token and other source chains to determine if a route is available to the desired chain. This process could be time consuming and considered inefficient.

Example: When transferring **any** token from Linea to Base, one is required to try every token in the list to discover the available options. Unfortunately, there is no automatic filtering in place to streamline this process. 

A suggestion would be to implement a feature that dynamically filters out the unavailable source options based on the selected destination. In other words, when a user selects a destination chain, only the available source options should be visible, streamlining the user interface. 

<img width="559" alt="Token option 1 unavailable" src="https://github.com/SocketDotTech/socket-DL/assets/118765079/b57a0bf7-a7c0-4a87-ba65-1128054f35e1">

<img width="553" alt="Token option 2 available" src="https://github.com/SocketDotTech/socket-DL/assets/118765079/5a68e5f7-210a-4d06-bd2f-766969cde325">

If not already proposed by others, I hope it garners consideration

**Comment by arthcp** [comment]
Hey @thegasbill, this repo is not the right place for improvements to bungee UI.
I suggest submitting the feedback via our [zendesk](https://socketdottech.zendesk.com/hc/en-us).
Thanks.
